### ISSUE TITLE
font sizing

### ISSUE THREAD

**Issue by sarahmagrish** [Ecotrust/F2S-MOI#24]
I think the fonts are quite a bit too big across the board - the top nav, all sections of the home page, about page. 

Can you check back on page 2 of MOI_WEB_COMP_HOME_SECTOR_STYLES.pdf up on drive and line those up?

**Comment by dnseminara** [comment]
I think my logic to convert pt to px must be wrong. Luckily it's just a function - so I can just change the value and it should apply to "most" font sizes.

Right now I have it that a pixel is 75% of a point. I'm not sure where I found that. So 42 pt font is roughly 31.5 pixels. I'm betting that 75% doesn't apply to everything. Maybe we can find a happy medium at check in.

**Comment by sarahmagrish** [comment]
## Totally. 50% maybe? Would be good for me to learn to build my comps with units that make more sense on the dev side

Sarah Cline | Design Director | Ecotrust
721 NW 9th Avenue, Suite 200 |  Portland, OR 97209
M (971) 344.7595 | www.ecotrust.orghttp://www.ecotrust.org/

Please note that I am out on Fridays.
