### ISSUE TITLE
Broken paypal image on oregonfarmtoschool.org

### ISSUE THREAD

**Issue by ldford** [Ecotrust/F2S-MOI#33]
@pollardld - not sure if you've had time to set up the dev environment for Farm to School Counts yet, but I noticed that the paypal button is broken - at least on FF and Chrome. IE is maybe how it's supposed to look (@kpelissier - check that out?). http://www.oregonfarmtoschool.org/about/ 

Chrome:
![image](https://cloud.githubusercontent.com/assets/6453589/19987166/f74e3d26-a1d6-11e6-8b55-55b88a0d9628.png)

IE:
![image](https://cloud.githubusercontent.com/assets/6453589/19987150/df7bea9a-a1d6-11e6-857c-b916604b5557.png)

**Comment by pollardld** [comment]
Thanks @ldford! There are a couple of issues with my install. I will get with Ryan tomorrow so he can help me fix it and then we will get this issue fixed.

**Comment by pollardld** [comment]
Paypal button fixed.

https://cl.ly/2k02441n1209
